# Task-016 : Zeros and Ones

# Answer :

In [2]:
import numpy

dimensions = tuple(map(int, input().split()))

print(numpy.zeros(dimensions, dtype=int))
print(numpy.ones(dimensions, dtype=int))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
