# Task-017 : Eye and Identity

# Answer :

In [ ]:
import numpy
numpy.set_printoptions(legacy='1.13')

N, M = map(int, input().split())

print(numpy.eye(N, M, k=0, dtype=float))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
